export const ButtonChangeTypes = {
    SWITCH_TO_CHALLENGE: 'SWITCH_TO_CHALLENGE',
    SWITCH_TO_PROJECT: 'SWITCH_TO_PROJECT',
    SWITCH_TO_ALL_ENROLLED: 'SWITCH_TO_ALL_ENROLLED',
    SWITCH_TO_IN_PROGRESS: 'SWITCH_TO_IN_PROGRESS',
    SWITCH_TO_COMPLETED: 'SWITCH_TO_COMPLETED',
}